theme: jekyll-theme-minimal

markdown: GFM

kramdown:
  syntax_highlighter_opts:
    guess_lang: true

timezone: 'Asia/Tokyo'

title: "My Open Manual"
description: ""

show_downloads: false

google_analytics:

favicon:
logo_src:
logo_href:
logo_background:

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      author:
        - "ProtectoRTD"